### ISSUE TITLE
Organizar wiki

### ISSUE THREAD

**Issue by Eduardojvr** [SpotifyApp/Spotify#1]
- [ ] Design
- [x] Integração
- [ ] Marketing
- [ ] Monetização
- [x] Música
- [ ] Usuário

**Comment by Lcunha** [comment]
Link de acesso. https://github.com/Eduardojvr/Spotify/wiki/Elicita%C3%A7%C3%A3o---M%C3%B3dulo:-Integra%C3%A7%C3%A3o-do-uso-do-Spotify-em-diferentes-Hardwares.
