### ISSUE TITLE
Elicitação 1 

### ISSUE THREAD

**Issue by Lcunha** [SpotifyApp/Spotify#2]
- [ ] Design
- [x] Integração
- [ ] Marketing
- [x] Monetização
- [x] Música
- [ ] Usuário

**Comment by aquiles23** [comment]
https://github.com/Eduardojvr/Spotify/wiki/Elicita%C3%A7%C3%A3o-de-requisitos-de-monetiza%C3%A7%C3%A3o

**Comment by Eduardojvr** [comment]
Métodos de Historytelling e Observação
https://github.com/Eduardojvr/Spotify/wiki/Plano-de-Elicita%C3%A7%C3%A3o-de-Requisitos-M%C3%BAsica
