### ISSUE TITLE
Elicitação 2

### ISSUE THREAD

**Issue by Lcunha** [SpotifyApp/Spotify#3]
- [ ] Design
- [x] Integração
- [ ] Marketing
- [x] Monetização
- [x] Música
- [ ] Usuário

**Comment by Lcunha** [comment]
Realizei a elicitação com o método de análise de protocolo na integração do Spotify no celular com o web browser.

**Comment by aquiles23** [comment]
https://github.com/Eduardojvr/Spotify/wiki/Elicita%C3%A7%C3%A3o-de-requisitos-de-monetiza%C3%A7%C3%A3o
